#!/usr/bin/python
'''
a quick view for file './BIFs'
'''

map(func, seq1,seq2,...) -> list  #返回序列的映射序列，序列个数==func参数个数
reduce(func, seq, init=None) -> value	#func为二元函数
filter(func, seq) ->subseq 	#返回子序列：items of func(item)==True 
compare rules
repr(val/cmd) or `val/cmd` -> value of val/cmd
float(str/num) -> float
hash(obj) -> integer (if hashable)
len(iterable) -> item numbers of iterable obj
max(seq) -> value
min(seq) -> value
sum(iterable) -> value
any(iterable) -> bool
all(iterable) -> bool
enumerate(iterable, count=0) -> enumerate-obj
range() -> list
xrange() -> iterator
reversed(seq) -> seq
sorted(iterable, cmp=None, key=None, reverse=False)
zip(seq1, seq2, seq3, ...)
locals() -> dict	#返回局部名字空间,变量或函数名做为键被引号包含，其值为键值
globals() -> dict	#返回全局名字空间	
