#!/usr/bin/python

#tuple
#------------注意事项----------
1.'(obj,)'
	只有一个元素的tuple，元素后需加一个逗号，否则不会被识别为元组
	list 则不用
	#>>> type((None))
	#<type 'NoneType'>
	#>>> type((12))
	#<type 'int'>
	
	#>>> type((None,))
	#<type 'tuple'>
	#>>> type((12,))
	#<type 'tuple'>

2.元组是不可变类型，但其可变元素可变
	#>>> t
	#(12, 3, 4, [23, 44, 66], 'we', 'we')
	#>>> t[3][0] = 'ch'
	#>>> t
	#(12, 3, 4, ['ch', 44, 66], 'we', 'we')


#--------------操作--------------
#	创建
1.t = (obj1, obj2, ...) #只有一个元素：'t = (obj1,)'
2.t = obj1, obi2, obj3,... #只有一个元素：'t = obj1,' #不推荐
3.t = tuple(seq)

