#!/usr/bin/python

chapter 10:
	Errors and Exceptions


----------------------------------------------------

'异常类'

__builtin__.object(exception-classes):
	-BaseException
		|-KeyboardInterrupt
		|-SystemExit
		|-GeneratorExit
		|-Exception
			|-StopIteration
			|-Warning
				...
			|-StandardError
				|-EOFError
				|-ValueError
				...

#注：可'$ pydoc exceptions' 查看完整信息

EOFError: (ctrl+d)，引发异常时不带异常信息
KeyboardInterrupt: (ctrl+c), 引发异常时不带异常信息	

-------------------------------------------------------

'捕获异常'

try-except-else-finally
	try-except
		try: pass
		except (xxxError, ...)[,reason]: pass
	
	try-except 捕获所有异常 
		1.裸except（不能带原因参数）
			try: pass
			except: reason = sys.exc_info()
		2.异常根类（可带原因参数）
			try: pass
			except BaseException[,reason]: pass

	try-except1-except2-...-else-finally

------------------------------------------------------

'with statement' 
	等价于 try-except-finally, 并回收资源
	仅作用于支持上下文协议的对象

	with mgr [as VAR]:
		BLOCK

	# mgr：支持上下文管理的对象， eg: file, thread.LockType
	# contextMgr 相关信息： ./statement/with_contextmgr.py
	# contextMgr 相关系统模块： contextlib

--------------------------------------------------------

'相关'

exceptions module
sys.exc_info()


