#!/usr/bin/python

class

--------------------------------------------------------------------------------
"List of class-type attribute"

T.__new__(cls, ...)	 #创建类cls的新对象, S为T的子类
					 #eg float.__new__(cls)

__slots__	#可替代__dict__以节约内存

__str__		#返回字符串
__repr__	#返回字符串，但不同于__str__返回的是非转义的原值

--------------------------------------------------------------------------------
"Concept"

绑定调用		#方法由实例对象调用 instance.method()
非绑定方式		#由类调用，并显示传入实例作为参数 class.method(instance)
					#应用场景：子类对象调用被遮蔽的父类方法
						#在子类定义的方法中
							# pclass.method(self, args)
							# 或: super(cclass,self).method(args)
实例方法		#方法需绑定或传入实例， 绑定方式中由解释器自动传入实例对象
					#eg: __init__(self),  myfun(self)
类方法			#方法需需绑定或传入类， 绑定方式中由解释器自动传入
					#eg:__new__(cls),  @classmethod \ def fun(cls, ...):pass
