#!/usr/bin/python

'pickle module'
	转换存储Python对象，使之存储传输方便, 称之:扁平化/序列化/顺序化数据
	增强版本 cPickle module
	相关模块: marshal

'应用'
	把python对象直接保存到文件，而不需要转换为字符串

# 读文件
f = open('xxx','r')
pickle.load(f) -> data; # exception: UnpicklingError

# 写文件
f = open('xxx', 'w')
pickle.dump(data, f)	# exception: PicklingError


Reference:
	https://docs.python.org/2.7/library/pickle.html?highlight=pickle
	http://blog.sina.com.cn/s/blog_54b14bb80100li1z.html

