#!/usr/bin/python

'module time'

* time() -> float   # curtime
* clock() -> float 	# cup time
* ctime(t=time()) -> str
gmtime(t=time()) -> time_struct


--------------------------------------------
备注：

* time(), clock()
	'''
	>>> time.ctime(time.clock())
	'Thu Jan  1 08:00:00 1970'
	>>> 
	>>> time.ctime(time.time())
	'Sun Jul  5 22:00:36 2015'
	'''

* time_struct
	tm_year : 完整年数，若想显示后两位，可(tm_year % 100)

* ctime([secs])
	secs存在上限， 超出上限会报错:ValueError
	'''
	>>> time.ctime(69999999999999999)
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	ValueError: unconvertible time
	>>> time.ctime(59999999999999999)	# 最大整数上限
	'Sat May 29 18:40:00 1901326280\n'
	'''
 
